return {
    name = "ChimeraVIP",
    version = "0.94",
    tested_upstream = "2.6",
    raw_base = "https://raw.githubusercontent.com/gnomidlo/ChimeraVIP/main/",
    changes = {
        "Cechy: delty i podsumowanie progresu po kazdym odczycie",
        "Historia: /cechy historia zastapilo osobny /progres",
        "Porzadki: progres scalony z cechami, /xp zostaje trackerem sesyjnym",
    },
    files = {
        "loader.lua",
        "src/init.lua",
        "src/core/bootstrap.lua",
        "src/core/util.lua",
        "src/core/settings.lua",
        "src/core/help.lua",
        "src/core/updater.lua",
        "src/integrations/chimera.lua",
        "src/integrations/defense_combat.lua",
        "src/theme/pastel.lua",
        "src/ui/quiet_footer.lua",
        "src/ui/settings_apply.lua",
        "src/ui/settings_panel.lua",
        "src/features/combat_colors.lua",
        "src/features/defense_tracker.lua",
        "src/features/auto_support.lua",
        "src/features/xp_tracker.lua",
        "src/features/stats.lua",
        "src/features/characters.lua",
        "src/features/characters_delete_ui.lua",
        "src/ui/characters_help_panel.lua",
        "src/features/containers.lua",
        "src/features/skills_view.lua",
        "src/features/weapon_info.lua",
        "src/ui/footer_controls.lua",
        "src/ui/module_controls.lua"
    }
}
